### ISSUE TITLE
'npm run gh-pages' fails at theme documentation

### ISSUE THREAD

**Issue by golfecholima** [Quartz/Chartbuilder#203]
```
Error: Theme documentation-theme-default not found
    at resolveTheme (/Users/workmcgerk/Desktop/repos/Chartbuilder-gl/node_modules/documentation/lib/resolve_theme.js:21:11)
    at makeHTML (/Users/workmcgerk/Desktop/repos/Chartbuilder-gl/node_modules/documentation/lib/output/html.js:53:21)
    at /Users/workmcgerk/Desktop/repos/Chartbuilder-gl/node_modules/documentation/bin/documentation.js:34:3
    at /Users/workmcgerk/Desktop/repos/Chartbuilder-gl/node_modules/documentation/index.js:86:7
    at /Users/workmcgerk/Desktop/repos/Chartbuilder-gl/node_modules/documentation/lib/input/dependency.js:41:5
    at ConcatStream.<anonymous> (/Users/workmcgerk/Desktop/repos/Chartbuilder-gl/node_modules/documentation/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:72:20)
    at ConcatStream.emit (events.js:166:7)
    at finishMaybe (/Users/workmcgerk/Desktop/repos/Chartbuilder-gl/node_modules/documentation/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:511:14)
    at endWritable (/Users/workmcgerk/Desktop/repos/Chartbuilder-gl/node_modules/documentation/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:521:3)

npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "docs"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! chartbuilder@2.3.0 docs: `documentation -t documentation-theme-default --github --format html -o api-docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chartbuilder@2.3.0 docs script 'documentation -t documentation-theme-default --github --format html -o api-docs'.
npm ERR! This is most likely a problem with the chartbuilder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     documentation -t documentation-theme-default --github --format html -o api-docs
npm ERR! You can get their info via:
npm ERR!     npm owner ls chartbuilder
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/workmcgerk/Desktop/repos/Chartbuilder-gl/npm-debug.log

npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "gh-pages"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! chartbuilder@2.3.0 gh-pages: `npm run build && npm run docs && mv api-docs build && gulp gh-pages`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chartbuilder@2.3.0 gh-pages script 'npm run build && npm run docs && mv api-docs build && gulp gh-pages'.
npm ERR! This is most likely a problem with the chartbuilder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && npm run docs && mv api-docs build && gulp gh-pages
npm ERR! You can get their info via:
npm ERR!     npm owner ls chartbuilder
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

**Comment by nsonnad** [comment]
I was a bit confused about how theming works I think because I had a weird local setup. I took out the theme declaration and it should work now. Are you able to pull and run `npm run docs` or `npm run gh-pages`?

**Comment by golfecholima** [comment]
Still getting an error after pulling and running `npm install` anew:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'gh-pages' ]
2 info using npm@2.14.12
3 info using node@v4.2.4
4 verbose run-script [ 'pregh-pages', 'gh-pages', 'postgh-pages' ]
5 info pregh-pages chartbuilder@2.3.0
6 info gh-pages chartbuilder@2.3.0
7 verbose unsafe-perm in lifecycle true
8 info chartbuilder@2.3.0 Failed to exec gh-pages script
9 verbose stack Error: chartbuilder@2.3.0 gh-pages: `npm run build && npm run docs && mv api-docs build && gulp gh-pages`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid chartbuilder@2.3.0
11 verbose cwd /Users/workmcgerk/Desktop/repos/gl-Chartbuilder
12 error Darwin 14.1.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "gh-pages"
14 error node v4.2.4
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error chartbuilder@2.3.0 gh-pages: `npm run build && npm run docs && mv api-docs build && gulp gh-pages`
17 error Exit status 1
18 error Failed at the chartbuilder@2.3.0 gh-pages script 'npm run build && npm run docs && mv api-docs build && gulp gh-pages'.
18 error This is most likely a problem with the chartbuilder package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm run build && npm run docs && mv api-docs build && gulp gh-pages
18 error You can get their info via:
18 error     npm owner ls chartbuilder
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by golfecholima** [comment]
`npm run docs` throws same error FWIW.

terminal error:

```
> chartbuilder@2.3.0 docs /Users/workmcgerk/Desktop/repos/gl-Chartbuilder
> documentation -t documentation-theme-default --github --format html -o api-docs

/Users/workmcgerk/Desktop/repos/gl-Chartbuilder/node_modules/documentation/bin/documentation.js:21
    throw err;
    ^

Error: Theme documentation-theme-default not found
    at resolveTheme (/Users/workmcgerk/Desktop/repos/gl-Chartbuilder/node_modules/documentation/lib/resolve_theme.js:21:11)
    at makeHTML (/Users/workmcgerk/Desktop/repos/gl-Chartbuilder/node_modules/documentation/lib/output/html.js:53:21)
    at /Users/workmcgerk/Desktop/repos/gl-Chartbuilder/node_modules/documentation/bin/documentation.js:34:3
    at /Users/workmcgerk/Desktop/repos/gl-Chartbuilder/node_modules/documentation/index.js:86:7
    at /Users/workmcgerk/Desktop/repos/gl-Chartbuilder/node_modules/documentation/lib/input/dependency.js:41:5
    at ConcatStream.<anonymous> (/Users/workmcgerk/Desktop/repos/gl-Chartbuilder/node_modules/documentation/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:72:20)
    at ConcatStream.emit (events.js:166:7)
    at finishMaybe (/Users/workmcgerk/Desktop/repos/gl-Chartbuilder/node_modules/documentation/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:511:14)
    at endWritable (/Users/workmcgerk/Desktop/repos/gl-Chartbuilder/node_modules/documentation/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:521:3)

npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "docs"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! chartbuilder@2.3.0 docs: `documentation -t documentation-theme-default --github --format html -o api-docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chartbuilder@2.3.0 docs script 'documentation -t documentation-theme-default --github --format html -o api-docs'.
npm ERR! This is most likely a problem with the chartbuilder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     documentation -t documentation-theme-default --github --format html -o api-docs
npm ERR! You can get their info via:
npm ERR!     npm owner ls chartbuilder
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/workmcgerk/Desktop/repos/gl-Chartbuilder/npm-debug.log
```

**Comment by nsonnad** [comment]
Huh not sure why it's still running that command as the latest `npm run docs` command should not specify the theme, it should just be:

    documentation --github --format html -o api-docs

as shown [here](https://github.com/Quartz/Chartbuilder/blob/master/package.json#L10).

**Comment by golfecholima** [comment]
Ooh, I must've not been synched up. Just tried again and it worked like a charm.

**Comment by nsonnad** [comment]
Glad to hear it!
